#os:
#    - windows
#    - linux

language: cpp

matrix:
    include:
        - os: linux
          env: 
          - OS="$TRAVIS_OS_NAME"
          - LUACC=./luac.cross
        - os: windows
          env: 
          - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
          - OS="$TRAVIS_OS_NAME"
          - LUACC=msvc/luac-cross/x64/Debug/luac.cross.exe
addons:
  apt:
    packages:
    - python-serial
    - srecord
    - luarocks
cache:
  - directories:
    - cache
script:
- echo OS is $OS $TRAVIS_OS_NAME
# http://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
- if [ "$OS" = "linux" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/ci-build-linux.sh; fi
- if [ "$OS" = "windows" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/ci-build-windows-ms.sh; fi
- if [ "$OS" = "linux" -a "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/pr-build.sh; fi
- cd "$TRAVIS_BUILD_DIR"
- echo "checking:"
- find lua_modules lua_examples tests/NTest* -iname "*.lua" -print0 | xargs -0 echo
- find lua_modules lua_examples tests/NTest* -iname "*.lua" -print0 | xargs -0 $LUACC -p
- cd tests/NTest
- if [ "$OS" = "linux" ]; then ../../$LUACC -e ../NTest/NTest_NTest.lua; fi
- cd "$TRAVIS_BUILD_DIR"
- if [ "$OS" = "linux" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/run-luacheck-linux.sh; fi
- if [ "$OS" = "windows" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/run-luacheck-windows.sh; fi
